### ISSUE TITLE
Request for Contract

### ISSUE THREAD

**Issue by nden** [astropy/astropy-project#342] opened 2023-05-09 13:41 UTC
### Full name

Edward Slavich

### Email

edward.j.slavich gmail.com

### Title
ASDF Developer - Language independent ASDF deserialization

### Project Team

- Edward Slavich, a Java developer, previous maintainer of astropy.io.misc.asdf and a contributor to astropy will be the main developer
- Brett Graham, Perry Greenfield and Nadia Dencheva will collaborate on this project but will not be funded by this proposal.

### Project Description

The [Advanced Scientific Data Format](https://asdf-standard.readthedocs.io/en/latest/) (ASDF) was developed to address shortcomings of the FITS format, like serializing complex WCS transformations or dealing with newer types of instrumentation (IFS, MSA), that FITS is effectively incapable of handling [(Thomas, B., Jenness. T. et al. (2015))](https://doi.org/10.1016/j.ascom.2015.01.009). A [Python library](https://asdf.readthedocs.io/en/latest/ ) was developed to implement the standard. [Extensions](https://github.com/asdf-format) to the standard define the schemas  (descriptions of how the relevant information should be saved, and used for validation) for astropy types and [asdf_astropy](https://asdf-astropy.readthedocs.io/en/latest/) is the Python package which  serializes astropy types using those extensions.

ASDF strives to be an archival, language-independent format. However, having only one implementation of the standard makes it difficult to achieve this as language dependent features can creep into the library resulting in writing out files that are difficult or impossible to read in other languages. This production of language specific files is antithetical to the archival goals for ASDF. The following project will address this problem by implementing an ASDF reader in a non-Python language. Despite the seeming contradiction of proposing work in another language, doing so will help cement ASDF as a suitable way of serializing Astropy features acceptable in the wider community. To accomplish this we will:

- Create a set of language independent reference files that will be used as the "gold standard" in testing new features in the Python an non-Python libraries.

- Develop an ASDF implementation in another language (Java) which can read the above-mentioned reference ASDF files. This will be a limited implementation of the standard supporting only reading. Writing and validation will not be supported within the scope of this project.

This achieves several goals. The reference files will be used for testing the Python library and "keeping it honest" ensuring it does not accidentally include Python specific features and thus preventing the use of the standard with other languages in the future. Having a small library in another language which reads these files as part of a testing suite ensures they are truly language independent. Many astropy objects are serializable to ASDF using asdf_astropy. Since the new library will be able to read these files, the ASDF format will serve as a bridge between Python/Astropy and libraries in other languages, opening new ways of interoperability of Astropy with other software packages and exposing the Astropy software to other communities. In the future we hope to have libraries in C/C++, Java, IDL, and other common languages. Java was selected because of the availability of an experienced Java developer who is willing to immediately begin work on this project, and who can accept Numfocus contracts directly   thus ensuring that the funds can be used this year. The choice of language at this phase is not as important as any language will ensure independence of the Python implementation.

### Project/Work

- Create reference files using the Python ASDF library.
- Set up tests in the Python ASDF library to use the reference files.
- Implement a Java library capable of opening and reading ASDF files.
- Implement tests in the Java library to open and read the reference files. Set them up to run on a schedule.
- Write documentation for the Java library.

### Hourly rate

The proposed hourly rate is $120/hour (negotiable)
The minimum hourly rate is $90/hour.

### Total work hours

This work is estimated to take 120 hours - 40 hours to write a prototype, 40 hours to write the tests, 40 hours for documentation, finalizing and publishing.

**Comment by hamogu** [comment] 2023-07-25 06:13
We discussed this at length in the Coordination Committee (Coco) and we decided that we can *not* approve this request.

The problem is that that the implementation proposed and funded here is explicitly not in Python. However, we are the Astro*py* project and the Astro*py* coordination committee. While the Coco can approve out-of-cycle funding requests, we do need to stay within the mainstream of Astropy. This project is connected, but slightly off-topic. Thus, we, the Coco cannot approve funding for this without explicit authorization from the community.

We suggest to put this funding request forward in the next regular cycle where the Astropy members all have a chance to weigh in and vote. The ultimate authority in Astropy lies with the voting members and if they decide that implementing ASDF in a second language to keep the Python implementation honest  is important enough that it should be funded from funds earmarked for development of Astropy itself, that's fine - it's just outside of what the Coco can approve right now.

I am just going to close this issue, but I encourage you open a pull request at the next open call for funding.

**Closed by hamogu** 2023-07-25 06:13 UTC
Labels: finance :moneybag:, funding :pray:

**Comment by pllim** [comment] 2023-07-25 13:55
Personal opinion here (not from CoCo): Having just come back from Scipy 2023 and seeing how much people were emphasizing Python performance with big data, if your future application focus on, say, ASDF integration with [zarr](https://zarr.dev/) that already has bindings with multiple languages including Python, it could be viewed favorably.

**Comment by nden** [comment] 2023-07-26 11:59
@hamogu Thanks to CoCo for considering the work and the recommendation!

@pllim ASDF has a zarr extension now - https://github.com/asdf-format/asdf-zarr
